FORMAT_BY_INTENT = {
    "deep_integration": (
        "Use this detailed integration implementation structure:\n"
        "1. First decision / supported path\n"
        "2. Assumptions and scope\n"
        "3. What this feature is and where setup happens\n"
        "4. Prerequisites and blockers\n"
        "5. Permissions and identities to confirm\n"
        "6. Step-by-step setup in the correct product UI\n"
        "7. Table/object selection and configuration\n"
        "8. Validation steps\n"
        "9. Troubleshooting checks\n"
        "10. Limitations / gotchas\n"
        "11. Fallback options\n"
        "12. What to collect if it fails\n"
    ),
    "deep_architecture": (
        "Use this detailed architecture/compliance response structure:\n"
        "1. Executive summary\n"
        "2. Explicit question-by-question answers\n"
        "3. Platform behavior\n"
        "4. Compliance/governance boundary\n"
        "5. Azure-specific considerations\n"
        "6. Downstream impact analysis\n"
        "7. Evidence gaps\n"
        "8. Recommended stance\n"
        "9. Exact questions to confirm\n"
    ),
    "deep_troubleshooting": (
        "Use this detailed Databricks support runbook structure:\n"
        "1. Immediate triage\n"
        "2. Most likely causes ranked by probability\n"
        "3. Step-by-step checks\n"
        "4. What to look for\n"
        "5. Isolation tests\n"
        "6. Fix actions by cause\n"
        "7. Validation steps\n"
        "8. Escalation package\n"
    ),
    "deep_implementation": (
        "Use this detailed hand-holding implementation structure:\n"
        "1. Assumptions\n"
        "2. Before you start\n"
        "3. Account/cloud setup steps\n"
        "4. Workspace setup steps\n"
        "5. Permissions/grants\n"
        "6. Validation commands/checks\n"
        "7. Common mistakes\n"
    ),
    "commands": (
        "Return only concrete steps and commands/checks.\n"
        "Do not recap prior answers.\n"
    ),
    "troubleshooting": (
        "Use this concise troubleshooting structure:\n"
        "1. Exact error / symptom\n"
        "2. Fastest safe triage path\n"
        "3. Most likely causes ranked by probability\n"
        "4. What to check, with exact UI/log/object names\n"
        "5. Fix actions by cause\n"
        "6. How to validate success\n"
        "7. What to collect if unresolved\n"
    ),
    "implementation": (
        "Use this concise implementation structure:\n"
        "1. Prerequisites\n"
        "2. Steps\n"
        "3. Validation\n"
        "4. Common mistakes\n"
    ),
    "architecture": (
        "Use this architecture response structure. Make it decision-grade, not generic.\n"
        "1. Direct answer\n"
        "2. Recommended architecture\n"
        "3. Decision matrix\n"
        "4. Governance and security boundary\n"
        "5. Performance and cost tradeoffs\n"
        "6. Databricks-backed data considerations\n"
        "7. Risks and validation checks\n"
        "8. Questions to confirm if documentation is incomplete\n"
        "\n"
        "Architecture requirements:\n"
        "- If the question compares Direct Lake, Import, and DirectQuery, include a table with when to use, avoid when, data movement/caching, freshness, performance, governance/security, and cost/capacity implications.\n"
        "- For Databricks-backed data, separate live query patterns, copied/cached patterns, mirrored/shortcut patterns, and semantic model ownership.\n"
        "- Do not imply Unity Catalog policies automatically govern every downstream Fabric or Power BI artifact. Explain where governance must be validated.\n"
        "- End with a practical recommendation and proof-of-concept checklist.\n"
    ),
    "comparison": (
        "Use this structure:\n"
        "1. Direct answer\n"
        "2. Comparison\n"
        "3. Recommendation\n"
    ),
    "competitive_positioning": (
        "MANDATORY: Use exactly this field escalation and competitive deal-handling structure with these exact section headings. The user wants scenario evaluation and how to handle it, not a generic product comparison.\n"
        "1. Situation Readout\n"
        "2. What The Customer Is Really Asking\n"
        "3. Competitive Motion / FUD Diagnosis\n"
        "4. Technical Truth Table\n"
        "5. Recommended Stance\n"
        "6. Who Needs To Be On The Call\n"
        "7. Customer-Ready Response\n"
        "8. Meeting Invite And Agenda\n"
        "9. Talk Track For The Call\n"
        "10. Landmines / What Not To Say\n"
        "11. Proof Points, Citations, And Evidence Gaps\n"
        "12. Internal Escalation And Next Actions\n"
        "\n"
        "Competitive deal-handling requirements:\n"
        "- Keep each section to 1-3 tight bullets unless the user asks for a full workshop document.\n"
        "- First evaluate the human/account situation: decision timeline, stakeholder concern, competitive pressure, renewal risk, and who is influencing whom.\n"
        "- Validate legitimate customer architecture concerns before countering competitor framing. Do not label everything as FUD.\n"
        "- For semantic-layer disputes, separate data governance/storage from semantic evaluation, metric definition, security enforcement, lifecycle management, and business consumption.\n"
        "- Name the exact people or role types needed on the call, such as Power BI semantic model SME, Fabric data engineering/OneLake SME, Azure Databricks/Unity Catalog SME, account owner, and roadmap/PG owner when required.\n"
        "- Rewrite unsafe draft language into customer-safe email copy when the user includes a draft.\n"
        "- Include what to say, what not to say, and why each landmine is risky.\n"
        "- Be precise about DirectQuery, Import, Direct Lake, mirroring, shortcuts, connector behavior, Metric Views, Unity Catalog, masking/security, cost, and storage.\n"
        "- Do not overclaim roadmap, governance inheritance, cost impact, or competitor limitations unless retrieved context supports it.\n"
        "- Do not make uncited scale, SLA, benchmark, or global-usage claims such as 'Power BI supports 100K+ users', 'millions of users', '99.9% uptime', or 'trillion queries' unless the retrieved context directly supports the claim. Use the customer's known scale instead.\n"
    ),
    "meeting_prep": (
        "Use this customer meeting prep structure:\n"
        "1. What the customer is really asking\n"
        "2. Recommended position to take\n"
        "3. Talk track\n"
        "4. Direct-answer table for the customer's specific questions\n"
        "5. Risks to surface\n"
        "6. Questions to ask live\n"
        "7. Follow-up actions\n"
        "\n"
        "Talk track requirements:\n"
        "- Write exact words the user can say on a customer call.\n"
        "- Start with the safest direct position.\n"
        "- Make the user sound confident, not evasive.\n"
        "- Separate platform behavior from customer compliance/governance decisions.\n"
        "- The spoken talk track itself should not be citation-heavy; keep citations in evidence notes or direct answers.\n"
        "- Include an 'If challenged' response for the most likely objection.\n"
        "- Include an 'Avoid saying' line when overclaiming would be risky.\n"
        "- Avoid absolute operational guarantees like 'will not break anything' unless explicitly supported by retrieved context.\n"
        "- Prefer technically/platform-enforced vs governance/compliance-driven language for risk boundaries.\n"
        "- Use customer-ready phrases like:\n"
        "  - The important distinction is...\n"
        "  - From a platform behavior standpoint...\n"
        "  - From a compliance governance standpoint...\n"
        "  - I would validate this before committing...\n"
        "  - The safe rollout path is...\n"
    ),
    "learning": (
        "MANDATORY: Use exactly this high-quality teaching structure and these section headings. Do not use the older headings 'Plain-English explanation', 'Why it matters', 'Simple example', and 'Common misconceptions' by themselves.\n"
        "1. Simple mental model\n"
        "2. What it is in one sentence\n"
        "3. Why it matters in real projects\n"
        "4. Core building blocks and how they relate\n"
        "5. How it works end-to-end in Azure Databricks\n"
        "6. Concrete real-world example\n"
        "7. What admins vs engineers vs analysts do\n"
        "8. Common misconceptions and gotchas\n"
        "9. Quick checklist to know you understood it\n"
        "Teaching requirements:\n"
        "- Use an analogy first, then map the analogy back to real Databricks objects.\n"
        "- Define jargon before using it heavily.\n"
        "- Include at least one object hierarchy or flow, such as metastore > catalog > schema > table.\n"
        "- Explain managed tables, external tables/locations, storage credentials, and grants when relevant.\n"
        "- End with a practical example the user could recognize in a real customer environment.\n"
    ),
    "deep_explanation": (
        "Use this deep explanation structure:\n"
        "1. Executive summary\n"
        "2. Core concept\n"
        "3. How it works end-to-end\n"
        "4. Design implications\n"
        "5. Risks / gotchas\n"
        "6. Validation checks\n"
        "7. When to use / not use\n"
    ),
    "explanation": (
        "Use this structure:\n"
        "1. Short answer\n"
        "2. Practical explanation\n"
        "3. Example\n"
        "4. Gotchas\n"
    ),
}
