TOPIC_CONFIG = {
    "powerbi_semantic_architecture": {
        "keywords": [
            "direct lake", "directquery", "direct query", "import mode",
            "power bi semantic model", "powerbi semantic model", "semantic models",
            "semantic model", "composite model", "dual mode", "aggregation table",
            "fabric semantic model", "power bi over fabric", "fabric capacity",
            "databricks-backed data", "databricks backed data", "databricks sql warehouse",
            "power bi connector", "databricks connector", "dax", "rls", "ols",
            "row-level security", "object-level security", "certified semantic model",
        ],
        "queries": [
            "{question}",
            "Power BI semantic model Direct Lake Import DirectQuery decision matrix Fabric governance performance cost",
            "Microsoft Fabric Direct Lake semantic model fallback behavior capacity limitations security validation",
            "Power BI DirectQuery Databricks SQL warehouse semantic model performance security limitations",
            "Power BI Import mode semantic model refresh incremental refresh governance security cache",
            "Power BI semantic models RLS OLS governance deployment pipelines certified datasets Fabric",
            "Microsoft Fabric OneLake Direct Lake Power BI semantic model Delta tables governance",
            "Azure Databricks Power BI connector DirectQuery Import semantic model Unity Catalog governance",
        ],
        "bad_terms": [
            "cluster-bootstrap", "init-script", "servicenow", "lakeflow", "model-serving",
        ],
    },
    "fabric_mirroring": {
        "keywords": [
            "fabric mirroring", "microsoft fabric mirroring", "mirror unity catalog",
            "mirroring unity catalog", "uc mirroring", "unity catalog mirroring",
            "mirror databricks to fabric", "mirror azure databricks",
            "databricks mirroring to fabric", "fabric mirrored database",
            "mirrored database", "fabric mirror", "mirror tables to fabric",
            "onelake mirroring", "databricks catalog to fabric",
            "databricks tables to fabric", "unity catalog to fabric",
            "fabric databricks connector", "fabric azure databricks mirroring",
            "use microsoft fabric to read data that is registered in unity catalog",
        ],
        "queries": [
            "{question}",
            "Microsoft Fabric mirrored database Azure Databricks supported sources limitations",
            "Microsoft Fabric mirror Azure Databricks tables mirrored database step by step prerequisites",
            "Microsoft Fabric mirror Azure Databricks Unity Catalog tables step by step",
            "Microsoft Fabric mirrored database Azure Databricks Unity Catalog prerequisites",
            "Fabric mirroring Azure Databricks Unity Catalog connection catalog schema tables",
            "Microsoft Fabric Databricks Unity Catalog mirroring limitations prerequisites",
            "Microsoft Fabric OneLake shortcut Unity Catalog Azure Databricks not mirroring limitations",
            "Use Microsoft Fabric to read data registered in Unity Catalog Azure Databricks EXTERNAL USE SCHEMA",
        ],
        "bad_terms": [
            "external-location", "external-locations", "external-tables",
            "storage-credential", "write-files", "read-files",
            "abfss", "storage-blob-data-contributor", "compliance-security-profile",
            "cluster-bootstrap", "spark-performance", "servicenow", "lakeflow",
            "enable-a-workspace-for-unity-catalog", "best-practices-for-dbfs",
        ],
    },
    "adls_private_access": {
        "keywords": [
            "storage account private access",
            "private access only",
            "public network access disabled",
            "storage account private endpoint",
            "adls private endpoint",
            "adls gen2 private endpoint",
            "adls gen2 private access",
            "databricks private storage",
            "databricks access private storage",
            "databricks connect to private storage",
            "databricks to adls private",
            "private network only storage",
            "private network storage account",
            "storage firewall databricks",
            "dfs private endpoint",
            "blob private endpoint",
            "privatelink.dfs.core.windows.net",
            "privatelink.blob.core.windows.net",
            "dbx-pub",
            "dbx-priv",
            "delegated subnet",
            "subnet has a delegation",
            "databricks_ui_api",
            "browser_auth",
            "private endpoint for databricks",
            "private endpoint for storage",
            "storage credential private endpoint",
            "access connector private storage",
            "vnet injected databricks storage private endpoint",
            "private endpoint on the storage account",
            "storage account has to use that endpoint",
            "private dns storage databricks",
            "databricks vnet storage private endpoint",
        ],
        "queries": [
            "{question}",
            "Azure Databricks access ADLS Gen2 storage account private endpoint dfs blob private DNS",
            "Azure Databricks VNet injected workspace ADLS Gen2 private endpoint privatelink.dfs.core.windows.net",
            "Databricks access storage account public network access disabled private endpoint DNS Unity Catalog",
            "Azure Databricks Unity Catalog storage credential external location ADLS Gen2 private endpoint Access Connector",
            "Databricks delegated subnet cannot create private endpoint Dbx-Pub Dbx-Priv storage account private endpoint",
            "Azure Storage private endpoint dfs blob private DNS Databricks compute VNet",
            "Databricks databricks_ui_api browser_auth private endpoint vs storage account private endpoint",
        ],
        "bad_terms": [
            "model-serving",
            "serving-endpoint",
            "endpoint-not-found",
            "fabric-mirroring",
            "compliance-security-profile",
            "csp",
            "servicenow",
            "lakeflow",
            "spark-performance",
        ],
    },
    "compliance_architecture": {
        "keywords": [
            "compliance security profile", "csp", "enhanced security and compliance",
            "enhanced security", "security profile", "compliance profile",
            "hipaa", "pci", "fedramp", "fips", "regulated data",
            "workspace compliance", "shared backend storage",
            "downstream impact", "resource groups", "all-or-nothing",
            "workspace-scoped", "workspace scoped", "compliance boundary",
        ],
        "queries": [
            "{question}",
            "Azure Databricks Compliance Security Profile workspace level setting enhanced security compliance",
            "Azure Databricks Compliance Security Profile HIPAA Azure workspace scoped behavior",
            "Databricks Compliance Security Profile shared storage workspace scope compliance boundary",
            "Databricks Compliance Security Profile downstream impact Azure resource group tenant non Databricks services",
        ],
        "bad_terms": [
            "unity-catalog", "external-location", "storage-credential",
            "write-files", "read-files", "serving-endpoint", "model-serving",
            "spark-performance", "lakeflow", "servicenow",
        ],
    },
    "cluster_bootstrap": {
        "keywords": [
            "bootstrap error", "bootstrap failed", "bootstrap failure",
            "cluster bootstrap", "spark cluster not starting", "cluster not starting",
            "cluster failed to start", "cluster fails to start", "cluster startup failed",
            "cluster startup", "cluster terminated", "cluster launch failure",
            "cluster pending", "stuck pending", "init script failed",
            "init script failure", "driver failed", "worker failed",
            "databricks cluster fails", "compute failed to start",
            "cluster event log", "instance acquisition", "cloud provider launch failure",
            "library install failed during startup", "bootstrap timeout",
        ],
        "queries": [
            "{question}",
            "Azure Databricks cluster bootstrap error troubleshooting cluster event log init scripts driver logs worker logs",
            "Azure Databricks cluster failed to start bootstrap error compute startup troubleshooting",
            "Databricks cluster startup failure init script bootstrap driver worker logs event log",
            "Azure Databricks cluster stuck pending bootstrap timeout networking DNS firewall outbound",
            "Databricks compute failed to start bootstrap error libraries init scripts instance pool policy",
            "Azure Databricks cluster launch failure quota capacity subnet NSG UDR NAT firewall DNS",
        ],
        "bad_terms": [
            "compliance-security-profile", "csp", "hipaa", "servicenow", "lakeflow",
            "model-serving", "endpoint-not-found",
        ],
    },
    "unity_catalog_setup": {
        "keywords": [
            "create unity catalog", "enable unity catalog", "set up unity catalog",
            "setup unity catalog", "unity catalog from scratch", "uc from scratch",
            "create metastore", "assign workspace to metastore",
            "databricks access connector", "first unity catalog",
            "enable uc", "create uc workspace", "unity catalog workspace",
            "hand holding unity catalog", "unity catalog end to end",
        ],
        "queries": [
            "{question}",
            "Azure Databricks Unity Catalog first time setup account console metastore workspace assignment",
            "Azure Databricks Unity Catalog create metastore ADLS Gen2 Access Connector Storage Blob Data Contributor",
            "Azure Databricks Unity Catalog workspace assignment catalog schema grants setup",
            "Azure Databricks Unity Catalog managed storage root storage account container access connector",
            "Azure Databricks Unity Catalog enable workspace prerequisites account admin metastore admin",
        ],
        "bad_terms": [
            "serving-endpoint", "model-serving", "endpoint-not-found",
            "spark-performance", "streamsets", "workday",
        ],
    },
    "lakeflow_ingestion": {
        "keywords": [
            "servicenow", "service now", "ingest data", "ingestion",
            "pipeline compute", "pipeline compute resources", "lakeflow",
            "connector", "managed connector", "arclight",
            "cannot move tables across catalogs", "permission_denied",
            "unauthorized access", "error starting pipeline compute resources",
        ],
        "queries": [
            "{question}",
            "Databricks ServiceNow ingestion Unity Catalog PERMISSION_DENIED pipeline compute resources",
            "Databricks Lakeflow Connect ServiceNow Unity Catalog permissions catalog schema pipeline",
            "Databricks ingestion pipeline compute resources Unity Catalog catalog schema permissions",
        ],
        "bad_terms": [
            "model-serving", "serving-endpoint", "endpoint-not-found",
            "foundation-model", "mlflow-deployments", "vector-search",
        ],
    },
    "uc_external_storage": {
        "keywords": [
            "another storage account", "write to another storage account",
            "external location", "storage credential", "write files", "read files",
            "write_files", "read_files", "abfss", "external table",
            "storage account", "storage permission",
        ],
        "queries": [
            "{question}",
            "Databricks Unity Catalog external location WRITE FILES READ FILES storage credential ADLS Gen2",
            "Databricks Unity Catalog external storage permissions storage credential external location",
            "Databricks GRANT READ FILES WRITE FILES external location",
            "Databricks ADLS Gen2 external location abfss storage credential Access Connector RBAC",
        ],
        "bad_terms": [
            "model-serving", "serving-endpoint", "endpoint-not-found",
            "feature-store", "online-feature-store",
        ],
    },
    "unity_catalog": {
        "keywords": [
            "unity catalog", "metastore", "catalog", "schema",
            "storage credential", "external location", "uc", "managed storage",
            "use catalog", "use schema", "create table", "modify",
            "show grants", "grant", "permissions", "privileges",
            "external use schema",
        ],
        "queries": [
            "{question}",
            "Databricks Unity Catalog privileges grants catalogs schemas tables",
            "Databricks Unity Catalog USE CATALOG USE SCHEMA CREATE TABLE MODIFY SELECT permissions",
            "Databricks Unity Catalog SHOW GRANTS catalog schema table permissions commands",
            "Databricks Unity Catalog storage credentials external locations",
        ],
        "bad_terms": [
            "query-federation", "databricks-apps", "dev-tools/cli",
            "dashboard", "ucx", "delta-sharing", "feature-store",
        ],
    },
    "networking": {
        "keywords": [
            "network", "vnet", "private endpoint", "nat gateway", "firewall",
            "outbound", "subnet", "nsg", "route table", "udr", "dns",
            "no public ip", "npip", "secure cluster connectivity",
            "storage firewall", "artifact", "artifacts",
        ],
        "queries": [
            "{question}",
            "Azure Databricks network troubleshooting VNet NSG UDR NAT firewall DNS outbound",
            "Azure Databricks no public IP NAT Gateway NSG UDR firewall outbound artifacts",
            "Azure Databricks secure cluster connectivity network requirements firewall ports",
        ],
        "bad_terms": ["release-notes", "query-federation", "databricks-apps"],
    },
    "spark_performance": {
        "keywords": [
            "slow spark", "spark performance", "spark ui", "shuffle", "spill",
            "skew", "slow job", "performance regression", "executor lost",
            "task retries", "longest stage", "slowness", "slow notebook",
            "slow code", "optimize", "optimization", "faster", "make it faster",
            "performance issue", "slow query", "slow dataframe", "slow df",
        ],
        "queries": [
            "{question}",
            "Databricks Spark UI troubleshooting slow job skew spill shuffle task retries",
            "Databricks Spark performance regression compare input rows bytes cluster runtime",
            "Databricks optimize slow Spark DataFrame code joins shuffle caching partitioning Delta Lake",
        ],
        "bad_terms": [],
    },
    "sql_warehouse": {
        "keywords": [
            "sql warehouse", "databricks sql", "serverless sql",
            "warehouse", "dbsql", "sql endpoint",
        ],
        "queries": [
            "{question}",
            "Databricks SQL warehouse serverless pro classic best practices",
            "Databricks SQL warehouse performance troubleshooting",
            "Databricks SQL warehouse permissions Unity Catalog",
        ],
        "bad_terms": [],
    },
    "model_serving": {
        "keywords": [
            "model serving", "serving endpoint", "mlflow",
            "feature serving", "ai model", "foundation model", "llm endpoint",
        ],
        "queries": [
            "{question}",
            "Databricks Model Serving endpoint foundation model APIs",
            "Databricks MLflow model serving endpoint deployment",
        ],
        "bad_terms": [],
    },
    "vector_search": {
        "keywords": [
            "vector search", "embedding", "embeddings", "rag",
            "similarity search", "mosaic ai", "index", "delta sync",
        ],
        "queries": [
            "{question}",
            "Databricks Vector Search endpoint index delta sync",
            "Databricks Mosaic AI Vector Search embeddings RAG",
        ],
        "bad_terms": [],
    },
    "architecture": {
        "keywords": [
            "architecture", "architect", "design", "solution",
            "blueprint", "reference architecture", "landing zone",
        ],
        "queries": [
            "{question}",
            "Azure Databricks architecture lakehouse governance networking compute storage security",
            "Databricks lakehouse architecture best practices operational excellence",
        ],
        "bad_terms": ["release-notes"],
    },
    "general": {
        "keywords": [],
        "queries": [
            "{question}",
            "Azure Databricks {question}",
            "Databricks documentation {question}",
            "Databricks best practices {question}",
        ],
        "bad_terms": [],
    },
}

GLOBAL_BAD_TERMS = [
    "archive/dev-tools/cli", "dev-tools/cli", "release-notes",
    "streamsets", "workday", "mysql", "customize-containers",
]
